apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: eventticketing
type: Opaque
data:
  jwt-secret: MjQ5NjZjOGE3NjNiM2EzZjdmMjY0Y2VmYjkzZDk1MTU5MTg0ZThjNWUyYWY1Yzk0ZTA1Mzg3MzcxZDQ3YTNmZD0=
