apiVersion: v1
kind: Secret
metadata:
  name: ticket-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_USER: ticketuser
  POSTGRES_PASSWORD: ticketpass
  POSTGRES_DB: etdb-tickets