package com.team22.eventticketing.sales.config;

import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import org.springframework.stereotype.Component;
import javax.sql.DataSource;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

@Component
public class SchemaRecoveryFilter implements Filter {

    private final DataSource dataSource;

    public SchemaRecoveryFilter(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {

        try (Connection conn = dataSource.getConnection()) {
            String dbName = conn.getMetaData().getDatabaseProductName();
            if (dbName.toLowerCase().contains("postgresql")) {
                ResultSet rs = conn.getMetaData().getTables(null, "public", "ticket_sales", null);
                if (!rs.next()) {
                    initSchema(conn);
                }
            }
        } catch (Exception e) {
            // log but don't block the request
        }

        chain.doFilter(request, response);
    }

    private void initSchema(Connection conn) throws Exception {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
                        CREATE TYPE payment_method AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'WALLET');
                    END IF;
                END $$
                """);
            stmt.execute("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sale_status') THEN
                        CREATE TYPE sale_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');
                    END IF;
                END $$
                """);
            stmt.execute("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'discount_type') THEN
                        CREATE TYPE discount_type AS ENUM ('PERCENTAGE', 'FIXED');
                    END IF;
                END $$
                """);
            stmt.execute("""
                CREATE CAST IF NOT EXISTS (varchar AS payment_method) WITH INOUT AS IMPLICIT
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS ticket_sales (
                    id bigint generated by default as identity primary key,
                    booking_id bigint not null,
                    user_id bigint not null,
                    amount float8 not null,
                    method payment_method not null,
                    status sale_status not null,
                    transaction_details jsonb,
                    created_at timestamp not null
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS promotions (
                    id bigint generated by default as identity primary key,
                    code varchar(255) not null unique,
                    discount_type discount_type not null,
                    discount_value float8 not null,
                    max_uses integer not null,
                    current_uses integer not null default 0,
                    expiry_date timestamp not null,
                    active boolean not null default true,
                    metadata jsonb
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS sale_promotions (
                    id bigint generated by default as identity primary key,
                    ticket_sale_id bigint not null references ticket_sales(id),
                    promotion_id bigint not null references promotions(id),
                    discount_applied float8 not null,
                    applied_at timestamp not null
                )
                """);
        }
    }
}