apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-configmap
  namespace: eventticketing
data:
  SPRING_APPLICATION_NAME: ticket-service
  SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-postgres:5432/etdb-tickets
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/eventticketingmongo?authSource=admin
  SPRING_CASSANDRA_CONTACT_POINTS: cassandra
  SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
  SPRING_CASSANDRA_KEYSPACE_NAME: eventticketingks
  FEIGN_BOOKING_SERVICE_URL: http://booking-service:8080
  FEIGN_EVENT_SERVICE_URL: http://event-service:8080
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_SALES_SERVICE_URL: http://sales-service:8080
