apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: eventticketing
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/etdb-users
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/eventticketingmongo?authSource=admin
  BOOKING_SERVICE_URL: http://booking-service:8080
